name: CI/CD for Nest.js

on:
  push:
    branches:
      - main # Change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Build Nest.js app
        run: npm run build # Use the appropriate build command for your project

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }} # Replace with your server's IP
          username: ${{ secrets.SSH_USERNAME }} # Replace with your SSH username
          password: ${{ secrets.SSH_PASSWORD }} # Add your SSH private key as a secret in GitHub
          port: 22
          script: |
            cd ~/workers/test-project/
            git pull
            npm i --force
            pm2 restart main
